import { test } from "node:test";
import assert from "node:assert/strict";
import { parseNumeric, profileData, cleanData, processNLQuery, generateKPIs, generateInsights, generateChartRecommendations } from "../src/lib/analytics-engine";
import { validateQueryPlan, queryWithGemini } from "../src/lib/gemini-query";
const rows = [{ id: 1, product: "A", region: "North", revenue: 100, date: "2026-01-01" }, { id: 99, product: "B", region: "South", revenue: 200, date: "2026-02-01" }];
const names = Object.keys(rows[0]);
const { profile, columnMetas } = profileData(rows,names);
const ask = (q:string) => processNLQuery(q,rows,profile,columnMetas);
test("even and odd median", () => { assert.equal(columnMetas.find(m=>m.name==="revenue")?.median,150); assert.equal(profileData([{x:3},{x:1},{x:2}],["x"]).columnMetas[0].median,2); });
test("strict currency/comma parsing and junk rejection",()=>{ for(const [v,n] of [["$100",100],["1,000",1000],["-12.5",-12.5]] as const) assert.equal(parseNumeric(v),n); for(const v of ["12abc","2026-01-01","1,2", "", Infinity]) assert.equal(parseNumeric(v),null); });
test("dates are not numeric",()=>{ assert.equal(columnMetas.find(m=>m.name==="date")?.type,"date"); assert.ok(!profile.numericColumns.includes("date")); });
test("filtered total",()=>assert.match(ask("total revenue in North").answer,/is 100/));
test("filtered count",()=>assert.match(ask("how many records in North?").answer,/1 records/));
test("explicit zero-match filter",()=>assert.match(ask("total revenue where region = Mars").answer,/No matching/));
test("unknown implicit filter refuses",()=>assert.match(ask("total revenue in Mars").answer,/No calculation/));
test("top by named measure, not ID",()=>assert.equal(ask("top product by revenue").chart?.data[0].product,"B"));
test("filtered average",()=>assert.match(ask("average revenue in North").answer,/is 100/));
test("complex unsupported conditions refuse",()=>assert.match(ask("sum revenue above 50").answer,/No calculation/));
test("cleaning + reprofile",()=>{const raw=[{revenue:"1,000"},{revenue:"2,000"}];const m=profileData(raw,["revenue"]);const c=cleanData(raw,m.columnMetas);assert.equal(profileData(c.cleanedRows,["revenue"]).columnMetas[0].mean,1500);});
test("quality never forced above 100",()=>assert.equal(cleanData(rows,columnMetas).report.qualityAfter,100));
test("empty data stays finite",()=>{const p=profileData([],[]).profile;assert.equal(p.uniqueness,0);assert.equal(p.qualityScore,0);});
test("trim and dedupe",()=>{const raw=[{name:" A "},{name:"A"}];assert.equal(cleanData(raw,profileData(raw,["name"]).columnMetas).cleanedRows.length,1);});
test("deterministic summaries",()=>assert.deepEqual(generateInsights(rows,profile,columnMetas,"Sales"),generateInsights(rows,profile,columnMetas,"Sales")));
test("no chronological KPI claims without dates",()=>{const r=rows.map(({revenue})=>({revenue}));const p=profileData(r,["revenue"]);assert.equal(generateKPIs(r,p.profile,p.columnMetas,"Sales").find(k=>k.name==="Total Revenue")?.change,undefined);});
test("filtered chart distribution reflects filtered rows",()=>{const selected=rows.slice(0,1),p=profileData(selected,names);const c=generateChartRecommendations(selected,p.profile,p.columnMetas);assert.ok(c.every(ch=>!ch.data.some(r=>Object.values(r).includes("South"))));});
test("Gemini plans reject SQL, unknown columns and unsupported filters",()=>{for(const p of [{operation:"sql"},{operation:"sum",column:"secret"},{operation:"sum",column:"revenue",sql:"delete"},{operation:"sum",column:"revenue",filters:[{column:"bad",value:"x"}]}])assert.equal(validateQueryPlan(p,columnMetas),null);});
test("Gemini disabled sends nothing",async()=>{process.env.GEMINI_ENABLED="false";assert.equal(await queryWithGemini("total revenue",rows,columnMetas),null);});
import { filterDatasetRows } from "../src/lib/dataset-filters";
test("multiple dashboard slicers intersect",()=>assert.equal(filterDatasetRows(rows,columnMetas,new URLSearchParams({filterCol:"region",filterVal:"North",filterCol2:"product",filterVal2:"B"})).length,0));
test("dashboard date period actually filters",()=>assert.equal(filterDatasetRows(rows,columnMetas,new URLSearchParams({period:"7d"}),new Date("2026-02-03T00:00:00Z")).length,1));
test("unknown date period fails instead of ignored",()=>assert.throws(()=>filterDatasetRows(rows,columnMetas,new URLSearchParams({period:"custom"}))));
test("invalid dates are not temporal",()=>assert.equal(profileData([{date:"2026-02-30"}],["date"]).columnMetas[0].type,"string"));
test("Gemini payload has schema and question, no rows",async()=>{
  process.env.GEMINI_ENABLED="true";process.env.GEMINI_API_KEY="test-placeholder";
  const original=globalThis.fetch;
  let sent="";
  globalThis.fetch=async (_url,options)=>{sent=String(options?.body);return Response.json({candidates:[{content:{parts:[{text:JSON.stringify({operation:"sum",column:"revenue",filters:[{column:"region",value:"North"}]})}]}}]});};
  try{assert.match((await queryWithGemini("total revenue in North",rows,columnMetas))!.answer,/is 100/);assert.ok(!sent.includes('"revenue":100'));assert.ok(!sent.includes('"product":"A"'));}finally{globalThis.fetch=original;delete process.env.GEMINI_API_KEY;process.env.GEMINI_ENABLED="false";}
});
test("grouped sum and comparison do not silently run global total",()=>{for(const q of ["total revenue by region","total revenue > 100"])assert.match(ask(q).answer,/No calculation/);});
test("column paid is not an identifier",()=>assert.notEqual(profileData([{paid:100},{paid:200}],["paid"]).columnMetas[0].semanticType,"identifier"));
test("negative status is not a completed record",()=>{const r=[{status:"not completed"},{status:"Completed"}];const p=profileData(r,["status"]);assert.equal(generateKPIs(r,p.profile,p.columnMetas,"Sales").find(k=>k.name==="Completion Rate")?.value,"50.0%");});
test("monthly chart aggregates totals not averages",()=>{const r=[{date:"2026-01-01",revenue:100},{date:"2026-01-02",revenue:200},{date:"2026-02-01",revenue:50},{date:"2026-03-01",revenue:60}];const p=profileData(r,["date","revenue"]);assert.equal(generateChartRecommendations(r,p.profile,p.columnMetas).find(c=>c.type==="line")?.data[0].revenue,300);});
